routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/dashboard', 'DashboardController@index')->middleware('auth');

Route::resource('data-opd','MasterDinasController')->middleware('auth');
Route::resource('kepala-opd','MasterKepalaDinasController')->middleware('auth');
Route::resource('data-temuan','MasterTemuanController')->middleware('auth');
Route::resource('data-penyebab','MasterSebabController')->middleware('auth');
Route::resource('data-rekomendasi','MasterRekomendasiController')->middleware('auth');
Route::resource('bidang-pengawasan','MasterBidangPengawasanController')->middleware('auth');
Route::resource('users','UsersController')->middleware('auth');

Route::get('tindak-lanjut/{id}', 'TindakLanjutTemuanController@index')->name('tindak-lanjut.index');
Route::post('tindak-lanjut', 'TindakLanjutTemuanController@store')->name('tindak-lanjut.store');
Route::get('tindak-lanjut/{id}/edit', 'TindakLanjutTemuanController@edit')->name('tindak-lanjut.edit');
Route::get('tindak-lanjut/download/{filename}', 'TindakLanjutTemuanController@download')->name('tindak-lanjut.download');
Route::put('tindak-lanjut/{id}/update', 'TindakLanjutTemuanController@update')->name('tindak-lanjut.update');
Route::get('tindak-lanjut/{id}/show', 'TindakLanjutTemuanController@show')->name('tindak-lanjut.show');
Route::get('tindak-lanjut/{id}/selesai', 'TindakLanjutTemuanController@selesai')->name('tindak-lanjut.selesai');

Route::get('rekap-temuan','LaporanTemuanController@index')->middleware('auth');
Route::get('rekap-temuan-detail/{opd}','LaporanTemuanController@rekapdetail')->middleware('auth');

Route::get('rekomendasi-temuan/{tahun}', 'LaporanTemuanController@rekomendasi_temuan')->name('rekomendasi-temuan')->middleware('auth');
Route::get('print-rekomendasi-temuan/{tahun}', 'LaporanTemuanController@print_rekomendasi_temuan')->name('print-rekomendasi-temuan')->middleware('auth');

Route::get('laporan-kelompok-temuan/{tahun}', 'LaporanTemuanController@kelompok_temuan')->name('laporan-kelompok-temuan')->middleware('auth');
Route::get('print-kelompok-temuan/{tahun}', 'LaporanTemuanController@print_kelompok_temuan')->name('print-kelompok-temuan')->middleware('auth');

Route::resource('temuan','DaftarTemuanController')->middleware('auth');
Route::resource('list-temuan','DaftarTemuanController')->middleware('auth');
Route::get('list-temuan-data/{dinas_id?}/{tahun?}/{bidang_id?}','DaftarTemuanController@data')->middleware('auth');
Route::get('detail-form/{daftar_id}/{dinas_id?}/{tahun?}/{bidang_id?}','DaftarTemuanController@form_detail')->middleware('auth');
Route::post('detail-temuan-update/{id}','DaftarTemuanController@update_detail')->middleware('auth');
Route::post('detail-temuan-delete','DaftarTemuanController@detail_destroy')->middleware('auth');
Route::post('detail-temuan-verifikasi','DaftarTemuanController@detail_verifikasi')->middleware('auth');

Auth::routes();
Route::get('logout',function(){
    Auth::logout();
    return redirect('login');
});
Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','nip','pangkat','golongan','jabatan','level','flag'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    function user()
    {
        return $this->hasOne('App\Models\PivotUserDinas','user_id');
    }
    
    function userkepala(){
		// return $this->hasMany('App\Models\MasterKepalaDinas','user_id');
		return $this->hasOne('App\Models\MasterKepalaDinas','user_id');
	}
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\MasterDinas;
use App\Models\PivotUserDinas;
use App\User;
use Validator;
class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user=User::where('level','!=',4)->with('user')->get();
        // dd($user[1]->user);
        $dinas=MasterDinas::all();
        return view('backend.pages.user.index')->with('users',$user)->with('dinas',$dinas);
    }

    public function store(Request $request)
    {
        Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required',
            'level' => 'required',
            'dinas_id' => 'required',
            'pangkat' => 'required',
            'golongan' => 'required',
            'jabatan' => 'required',
            'password' => 'required|confirmed',
        ])->validate();

        $insert = new User;
        $insert->name = $request->name;
        $insert->email = $request->email;
        $insert->password = bcrypt($request->password);
        $insert->level = $request->level;
        $insert->nip = $request->nip;
        $insert->pangkat = $request->pangkat;
        $insert->golongan = $request->golongan;
        $insert->jabatan = $request->jabatan;
        $insert->flag = $request->flag;
        $insert->save();
        $user_id=$insert->id;

        $u_dinas = new PivotUserDinas;
        $u_dinas->dinas_id = $request->dinas_id;
        $u_dinas->user_id = $user_id;
        $u_dinas->flag = $request->flag;
        $u_dinas->save();

        return redirect()->route('users.index')
            ->with('success', 'Anda telah memasukkan data baru.');
    }

    public function edit($id)
    {
        return User::where('id',$id)->with('user')->first();
    }

    public function update(Request $request, $id)
    {
        if (is_null($request->password) || is_null($request->password_confirmation)) {
            Validator::make($request->all(), [
                'name' => 'required',
                'email' => 'required',
                'level' => 'required',
                'dinas_id' => 'required',
                'pangkat' => 'required',
                'golongan' => 'required',
                'jabatan' => 'required',
            ])->validate();

            $update = User::find($id);
            $update->name = $request->name;
            $update->email = $request->email;
            $update->level = $request->level;
            $update->nip = $request->nip;
            $update->pangkat = $request->pangkat;
            $update->golongan = $request->golongan;
            $update->jabatan = $request->jabatan;
            $update->flag = $request->flag;
            $update->save();

            $u_dinas = PivotUserDinas::where('user_id',$id)->first();
            $u_dinas->dinas_id = $request->dinas_id;
            $u_dinas->flag = $request->flag;
            $u_dinas->save();

            return redirect()->route('users.index')
                ->with('success', 'Anda telah mengubah data pengguna.');
        }

        Validator::make($request->all(), [
            'name' => 'required',
            'email' => 'required',
            'level' => 'required',
            'dinas_id' => 'required',
            'pangkat' => 'required',
            'golongan' => 'required',
            'jabatan' => 'required',
            'password' => 'required|confirmed',
        ])->validate();

        $update = User::find($id);
        $update->name = $request->name;
        $update->email = $request->email;
        $update->password = bcrypt($request->password);
        $update->level = $request->level;
        $update->nip = $request->nip;
        $update->pangkat = $request->pangkat;
        $update->golongan = $request->golongan;
        $update->jabatan = $request->jabatan;
        $update->flag = $request->flag;
        $update->save();

        $u_dinas = PivotUserDinas::where('user_id',$id)->first();
        $u_dinas->dinas_id = $request->dinas_id;
        $u_dinas->flag = $request->flag;
        $u_dinas->save();

        return redirect()->route('users.index')
            ->with('success', 'Anda telah mengubah data pengguna.');
    }

    public function destroy($id)
    {
        $us=User::find($id);
        $us->delete();

        $u_dinas = PivotUserDinas::where('user_id',$id)->first();
        $u_dinas->delete();
        
        return redirect()->route('users.index')
            ->with('success', 'Anda telah menghapus data pengguna.');
    }
}

resources/views/backend/pages/user/index.blade.php
@extends('backend.layouts.master')

@section('title')
    <title>Data User</title>
@endsection
@section('modal')
	<div class="modal fade" id="modaltambah" tabindex="-1" role="dialog">
		<div class="modal-dialog" style="width:70%">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Tambah Data Pengguna</h4>
				</div>
				<div class="modal-body">
					<form action="{{ route('users.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <select name="level" class="form-control">
                                        <option value="">-- Pilih Level --</option>
                                        <option value="1">Administrator</option>
                                        <option value="2">Operator</option>
                                        <option value="3">Admin OPD</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <input name="name" type="text" class="form-control" placeholder="Nama">
                                </div>
                                <div class="form-group">
                                    <input name="email" type="text" class="form-control" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <input name="password" type="password" class="form-control" placeholder="Password">
                                </div>
                                <div class="form-group">
                                    <input name="password_confirmation" type="password" class="form-control" placeholder="Konfirmasi Password">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <select name="dinas_id" class="form-control" placeholder="OPD">
                                        <option value="">-- Pilih OPD --</option>
                                        @foreach ($dinas as $opd)
                                            <option value="{{$opd->id}}">{{$opd->nama_dinas}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <input name="nip" type="text" class="form-control" placeholder="NIP">
                                </div>
                                <div class="form-group">
                                    <input name="pangkat" type="text" class="form-control" placeholder="Pangkat">
                                </div>
                                <div class="form-group">
                                    <input name="golongan" type="text" class="form-control" placeholder="Golongan">
                                </div>
                                <div class="form-group">
                                    <input name="jabatan" type="text" class="form-control" placeholder="Jabatan">
                                </div>
                                <div class="form-group">
                                    <select name="flag" class="form-control">
                                        <option value="">-- Status Flag --</option>
                                        <option value="1">Aktif</option>
                                        <option value="0">Tidak Aktif</option>
                                    </select>
                                </div>
                            </div>
                        </div>
						
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<input type="submit" class="btn btn-success" value="Simpan">
				</div>
				</form>
			</div>
		</div>
	</div>

	<div class="modal fade" id="modalubah" tabindex="-1" role="dialog">
		<div class="modal-dialog" style="width:70%">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Ubah Data Pengguna</h4>
				</div>
				<div class="modal-body">
					<form id="form-update" method="POST">
						@csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <select name="level" class="form-control" id="level">
                                        <option value="">-- Pilih Level --</option>
                                        <option value="1">Administrator</option>
                                        <option value="2">Operator</option>
                                        <option value="3">Admin OPD</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <input id="name" name="name" type="text" class="form-control" placeholder="Nama">
                                </div>
                                <div class="form-group">
                                    <input id="email" name="email" type="text" class="form-control" placeholder="Email">
                                </div>
                                <div class="form-group">
                                    <input id="password" name="password" type="password" class="form-control" placeholder="Password">
                                    <span class="help-block">* Silahkan kosongkan jika tidak mengubah password</span>
                                </div>
                                <div class="form-group">
                                    <input id="password_confirmation" name="password_confirmation" type="password" class="form-control" placeholder="Konfirmasi Password">
                                    <span class="help-block">* Silahkan kosongkan jika tidak mengubah password</span>							
                                </div>
                            </div>
                            <div class="col-md-6">
                                
                                <div class="form-group">
                                    <select id="dinas_id" name="dinas_id" class="form-control" placeholder="OPD">
                                        <option value="">-- Pilih OPD --</option>
                                        @foreach ($dinas as $opd)
                                            <option value="{{$opd->id}}">{{$opd->nama_dinas}}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <input id="nip" name="nip" type="text" class="form-control" placeholder="NIP">
                                </div>
                                <div class="form-group">
                                    <input id="pangkat" name="pangkat" type="text" class="form-control" placeholder="Pangkat">
                                </div>
                                <div class="form-group">
                                    <input id="golongan" name="golongan" type="text" class="form-control" placeholder="Golongan">
                                </div>
                                <div class="form-group">
                                    <input id="jabatan" name="jabatan" type="text" class="form-control" placeholder="Jabatan">
                                </div>
                                <div class="form-group">
                                    <select id="flag" name="flag" class="form-control">
                                        <option value="">-- Status Flag --</option>
                                        <option value="1">Aktif</option>
                                        <option value="0">Tidak Aktif</option>
                                    </select>
                                </div>
                                
                            </div>
                            
                        </div>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<input type="submit" class="btn btn-success" value="Simpan Perubahan">
				</div>
				</form>
			</div>
		</div>
	</div>

	<div class="modal fade" id="modalhapus" tabindex="-1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Konfirmasi Hapus Data Pengguna</h4>
				</div>
				<div class="modal-body">
					<h5>Apakah anda yakin akan menghapus data ini?</h5>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<a class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('form-delete').submit();" style="cursor:pointer;">Ya, Saya Yakin</a>
					<form id="form-delete" method="POST" style="display: none;">
						@csrf
						@method('DELETE')
					</form>
				</div>
			</div>
		</div>
	</div>
@endsection

@section('content')
	<div class="col-md-12">
		<div class="widget">
			<header class="widget-header">
				<span class="widget-title">Data Pengguna</span>
				<a href="" class="btn btn-sm btn-success pull-right" data-toggle="modal" data-target="#modaltambah">+ Tambah Data</a>
			</header><!-- .widget-header -->
			<hr class="widget-separator">
			<div class="widget-body">
				<div class="table-responsive">
					<table id="table" data-plugin="DataTable" class="table table-striped" cellspacing="0" width="100%">
						<thead>
							<tr>
								<th style="width:15px;">#</th>
								<th>NIP</th>
								<th>Nama</th>
								<th>Email</th>
								<th>OPD</th>
								<th>Hak Akses</th>
								<th>Flag</th>
								<th>Aksi</th>
							</tr>
						</thead>
						<tbody>
							@foreach ($users as $key => $us)
								<tr>
									<td>{{ $key = $key + 1 }}</td>
									<td>{{ $us->nip }}</td>
									<td>{{ $us->name }}</td>
									<td>{{ $us->email }}</td>
									<td>{{ isset($us->user->dinas_id) ? $us->user->dinas->nama_dinas : '-' }}</td>
									
									@switch($us->level)
										@case(1)
											<td>Administrator</td>
										@break
										@case(2)
											<td>Operator</td>
										@break
										@case(3)
											<td>Admin OPD</td>
										@break
									@endswitch
                                    <td>
                                        @if ($us->flag==1)
                                            <span class="label label-primary">Aktif</span>
                                        @else
                                            <span class="label label-danger">Tidak Aktif</span>
                                        @endif
                                    </td>
									<td>
										<a class="btn btn-xs btn-warning btn-edit" data-toggle="modal" data-target="#modalubah" data-value="{{ $us->id }}" style="height:24px !important;">
											<i class="fa fa-edit"></i>
										</a>
										<a href="#" class="btn btn-xs btn-danger btn-delete" data-toggle="modal" data-target="#modalhapus" data-value="{{ $us->id }}" style="height:24px !important;">
											<i class="fa fa-trash"></i>
										</a>
									</td>
								</tr>
						@endforeach
						</tbody>
					</table>
				</div>
			</div><!-- .widget-body -->
		</div><!-- .widget -->
	</div>
@endsection

@section('footscript')
	<script>
		// binding data to modal edit
        $('#table').on('click', '.btn-edit', function(){
            var id = $(this).data('value')
			
            $.ajax({
                url: "{{ url('users') }}/"+id+"/edit",
                success: function(res) {
					$('#form-update').attr('action', "{{ url('users') }}/"+id)

					$('#name').val(res.name)
					$('#nip').val(res.nip)
					$('#email').val(res.email)
					$('#password').val(res.password)
					$('#password_confirmation').val(res.password)
					$('#level').val(res.level)
					$('#flag').val(res.flag)
					$('#dinas_id').val(res.user.dinas_id)
                    $('#pangkat').val(res.pangkat)
					$('#golongan').val(res.golongan)
					$('#jabatan').val(res.jabatan)
                }
            })
        })

		// delete action
        $('#table').on('click', '.btn-delete', function(){
            var id = $(this).data('value')
			$('#form-delete').attr('action', "{{ url('users') }}/"+id)			
        })
	</script>
@endsection